- .circleci/config.yml
- makefile
- package.json
- packages/dual-channel/package.json
- packages/orangutan/package.json
- packages/scrollable-image/package.json
- packages/sheet2code-ui/package.json
- packages/timeline/package.json
Problem description:
When `@twreporter/orangutan` build its webpack bundle, it needs the `lib` files of its dependencies in the same monorepo (ex: `@twreporter/dual-channel`, `@twreporter/scrollable-image`). But in original CI process, only the packages with version bumping will be built.
Solution:
~Build all packages before testing and buming version~ (this will cause unnecessary building for commits like document update, version bumping...etc)
~Use `lerna changed` with [filter options](https://github.com/lerna/lerna/tree/master/core/filter-options#--include-dependencies) to build the dependencies package before publishing~ (see https://github.com/twreporter/orangutan-monorepo/pull/20#issuecomment-610315206 )
Use root `prepublishOnly` hook to build all packages before publishing instead. …
> chore: fix ci build bug

- packages/dual-channel/README.md
- packages/dual-channel/src/index.js
@YuCJ 
I am wrong about `target:'node'` in this thread https://github.com/twreporter/orangutan-monorepo/pull/6#discussion_r397600275 .
Although `target:'node'` avoids webpack failure, however, the output files can not run on browser.
Because of `@twreporter/orangutan`, it imports `@twreporter/dual-channel` in [its entry file](https://github.com/twreporter/orangutan-monorepo/blob/master/packages/orangutan/src/index.js#L1).
`@twreporter/scrollable-image-ui` wants to webpack bundle `@twreporter/orangutan`.
It causes webpack bundle failures. 
Error message:
```
ERROR in /Users/nick/codes/@twreporter/orangutan/node_modules/gaxios/node_modules/https-proxy-agent/dist/agent.js
Module not found: Error: Can't resolve 'net' in '/Users/nick/codes/@twreporter/orangutan/node_modules/gaxios/node_modules/ …
```
> refactor: remove `Sheets` from pkg entry file

- babel.config.js
- dev/__test__/dependencies.test.js
- package.json
- packages/dual-channel/package.json
- packages/orangutan/package.json
- packages/scrollable-image-ui/package.json
- packages/scrollable-image/package.json
- packages/sheet2code-ui/package.json
- packages/timeline/package.json
- yarn.lock
As @taylrj found out, those es5 files (transpiled according to this `babel.config.js`) can not be bundled by webpack.
Even though webpack can build the bundles without any errors and warning, however, the browser will throw error like following one
```
Uncaught ReferenceError: exports is not defined
```
I revert this change for further development.
I will spend time digging it out, and see what is the root cause.
> Fix babel config

- packages/scrollable-image/src/components/scroll-horizontal.js
test page: https://keystone-preview.twreporter.org/a/test-scrollableimage
After images are loaded, [_handleBottomBoundaryLeave](https://github.com/twreporter/orangutan-monorepo/blob/d9bd773be6587fcd08c4f395d45f62c712cd0b6f/packages/scrollable-image/src/components/with-waypoints.js#L74) will be triggered and set `isActive` to be true.
The component's `position` will be `fixed` once `scroll` event is dispatched.  
This patch adds min-height to scrollable-image component to avoid
triggering `onLeave` event after images are loaded.
> fix(scrollable-image): avoid extraneous onLeave event

- packages/scrollable-image-ui/webpack.config.js
This patch uses unpkg url as scripts url in `index.html` instead of
relative path for path translation.
> fix(scrollable-image-ui): use unpkg url as the scripts url

- packages/sheet2code-ui/src/components/form.js
- Now user can retrieve file id from drive URL (https://drive.google.com/open?id=xxxxxxxxx&qqq=rrr)
- Replace negative list of characters with white list to take the id from the URL. So it won’t take `#` or `?` in the URL into id
> fix(sheet2code-ui): fix regex to retrieve id from url

- packages/dual-channel/dev/client-entry.js
- packages/dual-channel/dev/webpack.config.js
- packages/dual-channel/src/app/components/root.js
- packages/dual-channel/src/build-code/client.js
- packages/dual-channel/src/build-code/full-width-wrapper.js
- packages/dual-channel/src/build-code/index.js
User can extend the width of `dual-channel` to viewport's width
> feat(dual-channel): add full-width wrapper to dual-channel

- packages/scrollable-image/dev/test-embedded-code-server.js
- packages/scrollable-image/src/build-code/client.js
- packages/scrollable-image/src/build-code/full-width-wrapper.js
This PR includes [this change](https://github.com/twreporter/orangutan-monorepo/pull/49) that users can extend the embedded component width to viewport's width, not to be limited by its parent. 
It has been tested on staging cloud function: https://asia-east2-cloud-functions-268910.cloudfunctions.net/scrollable-image
And can be viewed in this post: https://keystone-preview.twreporter.org/a/test-scrollableimage
Thanks to @YuCJ 's effort.
> feat(scrollable-image): add full width wrapper

- packages/dual-channel/src/app/components/embedded-items/index.js
There are empty embedded items (only render grey container) in mobile when
animation field(圖片動畫效果) is blank in spreadsheet.
> fix(dual-channel): fix mobile embedded items not show

- packages/dual-channel/src/app/components/embedded-items/index.js
- packages/dual-channel/src/app/components/root.js
This is a quick fix because of users' complaints (see https://www.facebook.com/twreporter/posts/2636471363267386).
I already released this change in `@twreporter/dual-channel@2.1.1-beta.3`,  and deployed `@twreporter/dual-channel@2.1.1-beta.3` in latest cloud function.
Create this PR for further discussion.
> style(dual-channel): restrict mobile embedded item height less than 50vh

- packages/dual-channel/src/app/components/embedded-items/index.js
- packages/dual-channel/src/app/components/root.js
- packages/dual-channel/src/test-data/data.json
1. We provide a `50vh` height and `100%` width container for embedded items.
2. Infogram's embedded code will render itself according to the width of the container.
3. In our design guideline, infogram content should be square.
If we see the results on iPhone SE, the container we provid for embedded items will be 320px width and 284px (50vh) height.
However, infogram's embedded code will render itself in 320px width and 320px height (because of Premise 2. and 3.).
Part of the infogram content will be cropped.
Make sure the container's width is less than or equal to container's height.
Set `max-width: 50vh` on embedded item section.
> style(dual-channel): (mobile) render infogram embedded code well

- packages/sheet2code-ui/README.md
- packages/sheet2code-ui/src/components/app.js
- packages/sheet2code-ui/src/components/preview.js
Main updates:
- Fix uncatched error
- Add new props: `previewAllowToggleDisplay` and `previewDefaultDisplay` (For `scrollable-video`. It needs to measure the elements' sizes on mounting. So the elements cannot be hidden on mounting.)
- Fix DOM validation warning of nested p element
> Several updates of sheet2code-ui

- packages/scrollable-image-ui/webpack.config.js
This patch sets `useBuiltIns` to `entry` for `@babel/polyfill`
> fix(scrollable-image-ui): set `useBuiltIns` to `entry`

- packages/scrollable-video/src/components/scrollable-video.js
This patch wraps function dependency (`onCreatingScrollTriggerError`)
of `useEffect` into `useCallback` to ensure it doesn't change on
every render unless its own dependency also changes.
> fix(scrollable-video): add `useCallback` for dependency of `useEffect`

- packages/scrollable-video/package.json
- packages/scrollable-video/src/build-code/client.js
- yarn.lock
This patch adds AbortController polyfill for abortable fetch(),
especially for legacy version of browsers (e.g. safari 10.2) which
doesn't yet implement AbortController DOM API.
ref: https://github.com/mo/abortcontroller-polyfill
> chore(scrollable-video): add AbortController polyfill

- .circleci/config.yml
This patch updates config.yml for circleci to remove `packages/orangutan/node_module`s
from `save_cache` since the orangutan sub-packages has been removed.
> chore: remove `packages/orangutan/node_module`s from `save_cache`

- .circleci/config.yml
This patch updates circle-ci config to fix an issue where the release
commit on branch 'release' can not be pushed into 'master'.
> fix: update circle-ci config

- packages/timeline/src/build-code/inject-style-script.js
If we minify the Timeline JavaScript snippet, those multiple lines will
be concatenated into one line code. The missing `;` will cause the
JavaScript `SyntaxError` error.
> fix(timeline): add missing `;` to avoid `Uncaught SyntaxError`

- packages/dual-channel/src/app/components/embedded-items/index.js
Address [TWREPORTER-415](https://twreporter-org.atlassian.net/browse/TWREPORTER-415)
Before this patch, first embedded item fixes on top of viewport
before the dual-channel section enters on tablet, mobile devices.
This patch makes the first embedded item be sticked to the top of
the dual-channel section instead of the viewport to keep touch
interactions available and will not be hindered by the fixed
first item.
> fix(dual-channel): keep first embedded item unfixed before enter

- packages/dual-channel/src/app/constants/theme.js
Address [TWREPORTER-416](https://twreporter-org.atlassian.net/browse/TWREPORTER-416)
This patch updates the z-index to 1001 of mobile toc to keep the
hamburger button on top of @twreporter/universal-header component.
> fix(dual-channel): update z-index of mobile toc
